services:
  api-web:
    container_name: api-web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    ports:
      - "3000:8080"
      - "5005:5005"
    networks:
      - backend
    volumes:
      - ../:/app
    depends_on:
      - api-db
      - api-redis
  api-db:
    image: mysql:8.4
    container_name: api-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - portfolio-api-db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend
  api-redis:
    image: redis:7.2
    container_name: api-redis
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
  localstack:
    image: localstack/localstack
    container_name: localstack
    networks:
      - backend
    ports:
      - 4566:4566
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      # カンマ区切りの指定サービスのみ使用可能
      - SERVICES=s3,ses
    volumes:
      - localstack-volume:/var/lib/localstack
networks:
  backend:
volumes:
  portfolio-api-db:
  redis-volume:
  localstack-volume: