package portfolioapi.portfolioapi.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
public class Test {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column test.id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column test.uuid
   *
   * @mbg.generated
   */
  private String uuid;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column test.title
   *
   * @mbg.generated
   */
  private String title;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column test.description
   *
   * @mbg.generated
   */
  private String description;
}