openapi: 3.0.3
info:
  title: "API"
  version: "1.0.0"
tags:
  - name: Test
    description: testApiの作成
paths:
  /tests:
    get:
      operationId: listTests
      summary: Test一覧を取得する
      tags:
        - Test
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
            example: タイトル
            maxLength: 255
        - name: description
          in: query
          required: false
          schema:
            type: string
            example: 説明
            maxLength: 1000
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestRow"
    post:
      operationId: createTest
      summary: Testを生成する
      tags:
        - Test
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestRegistrationDto"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /tests/{uuid}:
    get:
      operationId: getTest
      summary: Testを1件取得する
      tags:
        - Test
      parameters:
        - name: uuid
          description: テストUUID
          in: path
          required: true
          schema:
            type: string
            example: a123456789012345678901234567890z
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestDto"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "common/common.yml#/components/schemas/ErrorResponse"
    patch:
      operationId: updateTest
      summary: Testを1件部分更新する
      tags:
        - Test
      parameters:
        - name: uuid
          description: テストUUID
          in: path
          required: true
          schema:
            type: string
            example: a123456789012345678901234567890z
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestRegistrationDto"
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
    delete:
      operationId: deleteTest
      summary: Testを1件削除する
      tags:
        - Test
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            example: a123456789012345678901234567890z
      responses:
        "200":
          description: OK
        "404":
          description: Not Found

components:
  schemas:
    TestRow:
      type: object
      properties:
        total:
          type: integer
          description: 総数
          example: 10
        dataList:
          type: array
          description: Test
          items:
            $ref: "#/components/schemas/TestDto"
    TestDto:
      type: object
      properties:
        uuid:
          type: string
          description: UUID
          example: a123456787890123456787890123456787890z
        title:
          type: string
          description: タイトル
          example: タイトル
        description:
          type: string
          description: 説明
          example: 説明文
    TestRegistrationDto:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          description: タイトル
          example: タイトルです
          maxLength: 255
          minLength: 1
        description:
          type: string
          description: 説明
          example: 説明です
          maxLength: 1000
          minLength: 1
